USE [CSS490]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [UniversityChat].[Roles]
(
	[RoleId] [int] NOT NULL,
	[RoleName] [varchar](50) NOT NULL,
	[RoleDesc] [varchar](250) NULL,
	
	CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
	(
		[RoleId] ASC
	)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF,
	 ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [UniversityChat].[Roles]
	ADD CONSTRAINT UNQ_Roles_RoleName
	UNIQUE([RoleName]);

SET ANSI_PADDING OFF
GO


