<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="UniversityChat.Index" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>University Chat</title>

    <link href="Content/site.css" rel="stylesheet" type="text/css" />
    <link href="Content/south-street/jquery-ui-1.10.0.custom.min.css" rel="stylesheet" type="text/css" />
    
    <script src="Scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="Scripts/jquery-ui-1.10.0.custom.min.js" type="text/javascript"></script>
    <script src="Scripts/jquery.signalR-1.0.0-rc2.js" type="text/javascript"></script>
    <script src="/signalr/hubs" type="text/javascript"></script>   <!-- autogenerated by SignalR -->

    <script src="Scripts/chat-data-source.js" type="text/javascript"></script>
    <script src="Scripts/chat-ui.js" type="text/javascript"></script>
    <script src="Scripts/web-client.js" type="text/javascript"></script>
</head>
<body>
    
    <div class="container">
        <div class="header">
            <h1><a href="/">University Chat</a></h1>
            <div class="login-container">
                <form action="" id="login-form">
                    <div>
                        <input type="text" size="25" id="username" name="username" placeholder="Anonymous" value="Anonymous" /><br />
                        <a href="">Sign Up</a>
                    </div>
                    <!--
                    <div>
                        <input type="password" size="25" name="password" placeholder="Password" /><br />
                        <a href="">Forgot Password?</a>
                    </div>
                    -->
                    <div>
                        <button id="sign-in-button" type="submit">Sign In</button><br />
                        <button>Feedback</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="chat-container">
            <div class="channels">
                <h4>Public Channels</h4>
                <ul class="channel-list">
                </ul>
                <button class="add-channel" disabled="disabled">Create a Channel</button>
                <button class="remove-channel" disabled="disabled">Remove a Channel</button>
            </div>
            <div class="active-chat">
                <h4>Click on a public channel to the left to join a chat room</h4>

                <div id="chat-tabs">
                    <ul class="tabs">
                        
                    </ul>
                    <div class="content">
                        
                    </div>
                </div>

                <form action="" id="chat-form">
                    <input type="text" id="message" disabled="disabled"/>
                    <input type="submit" id="sendmessage" value="Send" disabled="disabled" />
                    <input type="hidden" id="displayname" />
                </form>
            </div>
            <div class="users">
                <h4>Connected Users</h4>
                <div class="user-lists"></div>
            </div>
            
        </div>
        <div class="footer">
            <a href="">About University Chat</a> | <a href="">Privacy & Terms</a> | <a href="">Feedback</a>
        </div>
    </div>
</body>
</html>
