USE [master]
GO

CREATE DATABASE [CSS490]
GO

ALTER DATABASE [CSS490] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CSS490].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CSS490] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CSS490] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CSS490] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CSS490] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CSS490] SET ARITHABORT OFF 
GO

ALTER DATABASE [CSS490] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CSS490] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CSS490] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CSS490] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CSS490] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CSS490] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CSS490] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CSS490] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CSS490] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CSS490] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CSS490] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CSS490] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CSS490] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CSS490] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CSS490] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CSS490] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CSS490] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CSS490] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CSS490] SET  READ_WRITE 
GO

ALTER DATABASE [CSS490] SET RECOVERY FULL 
GO

ALTER DATABASE [CSS490] SET  MULTI_USER 
GO

ALTER DATABASE [CSS490] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CSS490] SET DB_CHAINING OFF 
GO


