USE [master];

IF NOT EXISTS(SELECT 1 FROM sys.databases WHERE name = 'ucdatabase')
	BEGIN
		
		CREATE DATABASE [ucdatabase];

		ALTER DATABASE [CSS490] SET COMPATIBILITY_LEVEL = 100;


		IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
			BEGIN
				EXEC [CSS490].[dbo].[sp_fulltext_database] @action = 'enable'
			END		

		ALTER DATABASE [CSS490] SET ANSI_NULL_DEFAULT OFF 
		

		ALTER DATABASE [CSS490] SET ANSI_NULLS OFF 
		

		ALTER DATABASE [CSS490] SET ANSI_PADDING OFF 
		

		ALTER DATABASE [CSS490] SET ANSI_WARNINGS OFF;
		

		ALTER DATABASE [CSS490] SET ARITHABORT OFF 
		

		ALTER DATABASE [CSS490] SET AUTO_CLOSE OFF 
		

		ALTER DATABASE [CSS490] SET AUTO_CREATE_STATISTICS ON 
		

		ALTER DATABASE [CSS490] SET AUTO_SHRINK OFF 
		

		ALTER DATABASE [CSS490] SET AUTO_UPDATE_STATISTICS ON 
		

		ALTER DATABASE [CSS490] SET CURSOR_CLOSE_ON_COMMIT OFF 
		

		ALTER DATABASE [CSS490] SET CURSOR_DEFAULT  GLOBAL 
		

		ALTER DATABASE [CSS490] SET CONCAT_NULL_YIELDS_NULL OFF 
		

		ALTER DATABASE [CSS490] SET NUMERIC_ROUNDABORT OFF 
		

		ALTER DATABASE [CSS490] SET QUOTED_IDENTIFIER OFF 
		

		ALTER DATABASE [CSS490] SET RECURSIVE_TRIGGERS OFF 
		

		ALTER DATABASE [CSS490] SET  DISABLE_BROKER 
		

		ALTER DATABASE [CSS490] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
		

		ALTER DATABASE [CSS490] SET DATE_CORRELATION_OPTIMIZATION OFF 
		

		ALTER DATABASE [CSS490] SET TRUSTWORTHY OFF 
		

		ALTER DATABASE [CSS490] SET ALLOW_SNAPSHOT_ISOLATION OFF 
		

		ALTER DATABASE [CSS490] SET PARAMETERIZATION SIMPLE 
		

		ALTER DATABASE [CSS490] SET READ_COMMITTED_SNAPSHOT OFF 
		

		ALTER DATABASE [CSS490] SET HONOR_BROKER_PRIORITY OFF 
		

		ALTER DATABASE [CSS490] SET  READ_WRITE 
		

		ALTER DATABASE [CSS490] SET RECOVERY FULL 
		

		ALTER DATABASE [CSS490] SET  MULTI_USER 
		

		ALTER DATABASE [CSS490] SET PAGE_VERIFY CHECKSUM  
		

		ALTER DATABASE [CSS490] SET DB_CHAINING OFF 
		
	END



